### ISSUE TITLE
how to upload embeddings from local .npz file to the faceDB

### ISSUE THREAD

**Issue by ahmedmuzammilAI** [shhossain/FaceDB#8]
Hi, can you please let me know how I can upsert my local embeddings (saved to .npz file) generated from my own embedding model to the vector database, i tried but i cannot find a way to do it, Thanks in advance!

**Comment by shhossain** [comment]
Here is how to open a `.npz` file:
https://stackoverflow.com/questions/31368710/how-to-open-an-npz-file
