### ISSUE TITLE
The  variable PINECONE_ENVIRONMENT  is  is deprecated.

### ISSUE THREAD

**Issue by SebastiaoNunes** [shhossain/FaceDB#9]
The currently version of pinecone used only PINECONE_API_KEY to connect.
The key PINECONE_ENVIRONMENT is deprecated.

Ex:

pc = Pinecone(api_key='YOUR_API_KEY')

**Comment by shhossain** [comment]
I've fixed this issue. Will be available on pypi after some tests.
